spring.application.name=YoutubeSummarizer
server.port=8080
deepseek.api.key=sk-xxxxxx
proxy.host=proxy-us.proxy-cheap.com
proxy.port=5959
proxy.username=your_username_here
proxy.password=your_password_here
